<?php
/**
 * @file
 * Code for the GIE Dashboard feature.
 */

include_once 'gie_dashboard.features.inc';

/*
 * Implements hook_ctools_plugin_directory()
 */
function gie_dashboard_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_search_api_solr_query_alter().
 *
 * Adds multiple IDs for MLT call
 */
function gie_dashboard_search_api_solr_query_alter(array &$call_args, SearchApiQueryInterface $query) {
  $id = search_api_solr_site_hash();
  $nids =  &drupal_static('_mlt_nids');
  $node_index = 'id:"' . $id . '-default_node_index-' . $nids[0] . '"';

  // Make sure it's the query we want, could also check reference of query
  if ($node_index == $call_args['query']) {
    $index = 1;
    $count = count($nids);

    $call_args['query'] = 'id:(';
    foreach ($nids as $nid) {
      $call_args['query'] .= '"' . $id . '-default_node_index-' . $nid . '"';
      if ($index < $count) {
        $call_args['query'] .= ' OR ';
      }
      $index++;
    }
    $call_args['query'] .= ')';
  }
}

/*
 * Implements hook_form_FORM_ID_alter().
 */
function gie_dashboard_form_user_profile_form_alter(&$form, &$form_state) {
  $admin_role = user_role_load_by_name('administrator');
  $community_role = user_role_load_by_name('Program Community Manager');
  // Set field visibility based on whether the user is an admin
  if (!(user_has_role($admin_role->rid) || user_has_role($community_role->rid))) {
    $form['field_featured']['#type'] = 'hidden';
  }
}

/**
 * Implements hook_views_pre_views_pre_view().
 */
function gie_dashboard_views_pre_view($view) {
  if ($view->name == 'dashboard' && $view->current_display == 'user_funding_opportunities') {
    _gie_data_viz_init();
  }
}

function gie_dashboard_views_pre_render(&$view) {
  if ($view->name == 'dashboard' && $view->current_display == 'user_funding_opportunities' && !empty($view->result)) {
    foreach ($view->result as $key => $result) {
      if (!empty($result->field_field_funding_deadline[0]['raw']['value']) && !empty($result->field_field_funding_link[0]['raw']['value'])) {
        $deadline = $result->field_field_funding_deadline[0]['raw']['value'];
        $deadline = strtotime($deadline);
        // The deadline has passed
        if (!empty($deadline) && is_numeric($deadline) && strtotime('now') > $deadline) {
          $result->field_field_funding_deadline[0]['rendered']['#markup'] = '<span class="gie-dashboard-funding-op-status">Closed</span>';
          // The deadline is open
        }
        else {
          $result->field_field_funding_deadline[0]['rendered']['#markup'] = '<a class="button button--highlight" href="' . $result->field_field_funding_link[0]['raw']['value'] . '">Apply</a>';
        }
      }
    }
  }
}

/**
 * Implements hook_menu().
 */
function gie_dashboard_menu() {
  $items = array();
  $items['gie_dashboard/recommended_innovations'] = array(
    'title' => 'Recommended Innovations',
    'page arguments' => array('dashboard_recommended_innovations_form', 2),
    'page callback' => 'drupal_get_form',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['gie_dashboard/recommended_funding'] = array(
    'title' => 'Recommended Funding',
    'page arguments' => array('dashboard_recommended_funding_form', 2),
    'page callback' => 'drupal_get_form',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['gie_dashboard/my_portfolio'] = array(
    'title' => 'My Portfolio',
    'page arguments' => array('dashboard_my_portfolio_form', 2),
    'page callback' => 'drupal_get_form',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['gie_dashboard/my_network'] = array(
    'title' => 'My Network',
    'page arguments' => array('dashboard_my_network_form', 2),
    'page callback' => 'drupal_get_form',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}

function gie_dashboard_dummy_data($original_user_uid = NULL, $pieces = NULL) {
  $original_user_uid = !empty($original_user_uid) ? $original_user_uid : 1;
  $pieces = !empty($pieces) ? $pieces : 6;

  // Add the skill match
  if ($original_user_uid != 1) {
    $user = user_load($original_user_uid);
    $user->field_user_interests = array(
      LANGUAGE_NONE => array(
        array(
          'delta' => 0,
          'tid' => '545'
        )
      )
    );
    $user->field_term_sector = array(
      LANGUAGE_NONE => array(
        array(
          'delta' => 0,
          'tid' => '419'
        )
      )
    );
    user_save($user);
  }

  //Pragmatically Create Node Content For Dynamic Exchange Form

  $users = gie_dashboard_create_user($pieces);
  $rand_user = array_rand($users);
  $random_time_last_month = rand(strtotime('first day of last month'), strtotime('last day of last month'));
  // Last Access
  gie_dashboard_create_node('organization', $users[$rand_user], $pieces);
  gie_dashboard_create_node('funding', $original_user_uid, $pieces, array(
    'field_funding_grant_award_value' => 100000,
//    'field_term_topic' => 545,
    'field_term_sector' => 419,
    'field_funding_deadline' => array('value' => date('Y-m-d h:i:s', rand(strtotime('first day of last month'), strtotime('last day of last month')))),
    'field_funding_link' => 'http://google.com'
  ));
  gie_dashboard_create_node('innovation', $users[$rand_user], $pieces);

  $nids = array();
  // Last Month
  $month_users = gie_dashboard_create_user($pieces);
  $org_nids = gie_dashboard_create_node('organization', $users[$rand_user], $pieces);
  $funding_nids = gie_dashboard_create_node('funding', $users[$rand_user], $pieces, array('field_funding_grant_award_value' => 100000));
  $innovation_nids = gie_dashboard_create_node('innovation', $original_user_uid, $pieces);

  $nids = array_merge($org_nids, $funding_nids, $innovation_nids);
  // Random time during last month

  db_update('node')
    ->fields(array(
      'changed' => $random_time_last_month
    ))
    ->condition('nid', array($nids))
    ->execute();

  db_update('users')
    ->fields(array(
      'created' => $random_time_last_month
    ))
    ->condition('uid', array($month_users))
    ->execute();

  // People comment on admin content
  $comment = (object) array(
    'cid' => NULL,
    'nid' => $innovation_nids[array_rand($innovation_nids)],
    'node_type' => 'innovation',
    'pid' => 0,
    'uid' => $users[$rand_user],
    'status' => COMMENT_PUBLISHED,
    'subject' => devel_generate_word(mt_rand(6, 12)),
    'hostname' => ip_address(),
    'language' => LANGUAGE_NONE,
    'comment_body' => array(LANGUAGE_NONE => array(devel_generate_word(mt_rand(6, 12)))),
  );
  comment_save($comment);


  foreach ($users as $key => $user) {
    $account = user_load($user);
    $other_users = array_diff($users, array($user));
    $rando_not_me = $other_users[array_rand($other_users)];

    // People follow admin
    flag('flag', 'follow', $original_user_uid, $account, TRUE);

    // People follow your content
    flag('flag', 'favorite', $innovation_nids[$key], $account, TRUE);

    // Friend creates content
    $generated_content = gie_dashboard_create_node('innovation', $user, 1, array('field_term_topic' => 545));

    // Original User Follows Content
    flag('flag', 'favorite', $generated_content[0], user_load($original_user_uid), TRUE);

    //Friend follows content
    flag('flag', 'favorite', $generated_content[0], user_load($rando_not_me), TRUE);

    //Friend follows Friend of Friend
    flag('flag', 'follow', $user, user_load($rando_not_me), TRUE);

    //Friend comments on content
    $comment = (object) array(
      'cid' => NULL,
      'nid' => $generated_content,
      'node_type' => 'innovation',
      'pid' => 0,
      'uid' => $rando_not_me,
      'status' => COMMENT_PUBLISHED,
      'subject' => devel_generate_word(mt_rand(6, 12)),
      'hostname' => ip_address(),
      'language' => LANGUAGE_NONE,
      'comment_body' => array(LANGUAGE_NONE => array(devel_generate_word(mt_rand(6, 12)))),
    );
    comment_save($comment);
  }
  // Check for a Featured Node
  // If not found, add one
  $featured_node = db_query('SELECT COUNT(entity_id) FROM field_data_field_featured WHERE field_data_field_featured.field_featured_value = 1')->fetchField();
  if (empty($featured_node) || $featured_node < 1) {
    $random_innovation = db_query('SELECT nid FROM node WHERE node.type = :innovation ORDER BY RAND() LIMIT 1', array(':innovation' => 'innovation'))->fetchField();
    $node = node_load($random_innovation);
    $node->field_featured_innovation[$node->language][]['value'] = 1;
    node_save($node);
  }

  watchdog('gie_dashboard', 'Completed Dashboard Data Provision');

}

function gie_dashboard_create_node($type, $uid, $pieces, $payload = NULL) {
  $path = drupal_get_path('module', 'devel_generate');
  require_once($path . '/devel_generate.inc');
  $nodes = array();

  for ($x = 1; $x <= $pieces; $x++) {
    $node = new stdClass();
    $node->title = devel_create_greeking(1, TRUE);
    $node->type = $type;
    node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
    $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
    $node->uid = $uid;
    $node->status = 1; //(1 or 0): published or not
    $node->comment = 2; // 0 = comments disabled, 1 = read only, 2 = read/write

    if (!empty($payload['field_funding_grant_award_value'])) {
      $node->field_funding_grant_award_value[$node->language][]['value'] = $payload['field_funding_grant_award_value'];
    }

    if (!empty($payload['field_term_topic'])) {
      $node->field_term_topic[$node->language][]['tid'] = $payload['field_term_topic'];
    }

    if (!empty($payload['field_funding_deadline'])) {
      $node->field_funding_deadline[$node->language][]['value'] = $payload['field_funding_deadline'];
    }

    if (!empty($payload['field_term_sector'])) {
      $node->field_term_sector[$node->language][]['tid'] = $payload['field_term_sector'];
    }

    if (!empty($payload['field_funding_link'])) {
      $node->field_funding_link[$node->language][]['value'] = $payload['field_funding_link'];
    }

    $node = node_submit($node); // Prepare node for saving
    node_save($node);
    $nodes[] = $node->nid;
  }

  return $nodes;
}

function gie_dashboard_create_user($pieces, $name = NULL, $payload = NULL) {
  $path = drupal_get_path('module', 'devel_generate');
  require_once($path . '/devel_generate.inc');
  $users = array();
  if (count($pieces) > 1 && !empty($name)) {
    return;
  }
  for ($x = 1; $x < $pieces; $x++) {
    $user_name = !empty($name) ? $name : devel_generate_word(mt_rand(6, 12));
    //This will generate a random password, you could set your own here
    $password = user_password(8);
    $email = 'test@' . devel_generate_word(mt_rand(6, 12)) . '.com';
    //set up the user fields
    $fields = array(
      'name' => $user_name,
      'mail' => $email,
      'pass' => $password,
      'status' => 1,
      'init' => 'email address',
      'roles' => array(
        DRUPAL_AUTHENTICATED_RID => 'authenticated user',
      ),
    );

    //the first parameter is left blank so a new user is created
    $user = user_save('', $fields);
    $user->field_user_interests = array(
      LANGUAGE_NONE => array(
        array(
          'delta' => 0,
          'tid' => '545'
        )
      )
    );
    $user->field_term_sector = array(
      LANGUAGE_NONE => array(
        array(
          'delta' => 0,
          'tid' => '419'
        )
      )
    );
    user_save($user);
    // If you want to send the welcome email, use the following code

    // Manually set the password so it appears in the e-mail.
    $user->password = $fields['pass'];

    $users[] = $user->uid;
  }
  return $users;
}

function dashboard_recommendation_engine($bundle, $filter) {
  global $user;
  $matches = array();
  $follow_user = flag_load('follow');
  $favorite = flag_load('favorite');
  $display_items = 12;

  switch ($filter) {
    case 'my_sectors':

      $matches = db_query_range("SELECT DISTINCT node.nid FROM node
      LEFT JOIN field_data_field_term_sector sector_1 ON node.nid = sector_1.entity_id AND (sector_1.entity_type = 'node' AND sector_1.deleted = '0')
      INNER JOIN taxonomy_term_data  ON sector_1.field_term_sector_tid = taxonomy_term_data.tid
      INNER JOIN field_data_field_term_sector sector_2 ON taxonomy_term_data.tid = sector_2.field_term_sector_tid AND (sector_2.entity_type = 'user' AND sector_2.deleted = '0')
      INNER JOIN users ON sector_2.entity_id = users.uid
      WHERE (( (users.uid = :uid ) )AND(( (node.status = '1') AND (node.type IN (:bundle)) ))) ORDER BY node.changed DESC", 0, $display_items, array(
        ':uid' => $user->uid,
        ':bundle' => $bundle
      ))->fetchCol();

      break;

    case 'my_topics':

      $matches = db_query_range("SELECT DISTINCT node.nid FROM node
      LEFT JOIN field_data_field_term_topic term_1 ON node.nid = term_1.entity_id AND (term_1.entity_type = 'node' AND term_1.deleted = '0')
      INNER JOIN taxonomy_term_data  ON term_1.field_term_topic_tid = taxonomy_term_data.tid
      INNER JOIN field_data_field_user_interests ON taxonomy_term_data.tid = field_data_field_user_interests.field_user_interests_tid AND (field_data_field_user_interests.entity_type = 'user' AND field_data_field_user_interests.deleted = '0')
      INNER JOIN users ON field_data_field_user_interests.entity_id = users.uid
      WHERE (( (users.uid = :uid ) )AND(( (node.status = '1') AND (node.type IN (:bundle)) ))) ORDER BY node.changed DESC", 0, $display_items, array(
        ':uid' => $user->uid,
        ':bundle' => $bundle
      ))->fetchCol();

      break;

    case 'my_skills':

      $matches = db_query_range("SELECT DISTINCT node.nid FROM node
      LEFT JOIN field_data_field_innovation_assistance ON node.nid = field_data_field_innovation_assistance.entity_id AND (field_data_field_innovation_assistance.entity_type = 'node' AND field_data_field_innovation_assistance.deleted = '0')
      INNER JOIN taxonomy_term_data  ON field_data_field_innovation_assistance.field_innovation_assistance_tid = taxonomy_term_data.tid
      INNER JOIN field_data_field_user_assistance ON taxonomy_term_data.tid = field_data_field_user_assistance.field_user_assistance_tid AND (field_data_field_user_assistance.entity_type = 'user' AND field_data_field_user_assistance.deleted = '0')
      INNER JOIN users ON field_data_field_user_assistance.entity_id = users.uid
      WHERE (( (users.uid = :uid ) )AND(( (node.status = '1') AND (node.type IN (:bundle)) ))) ORDER BY node.changed DESC", 0, $display_items, array(
        ':uid' => $user->uid,
        ':bundle' => $bundle
      ))->fetchCol();

      break;

    case 'my_friends':

      $matches = db_query_range('SELECT favorite_node.entity_id FROM flagging
      INNER JOIN flagging reverse_flagging on flagging.uid = reverse_flagging.entity_id
      INNER JOIN flagging favorite_node on flagging.uid = favorite_node.uid
      INNER JOIN node on node.nid = favorite_node.entity_id
      WHERE node.type IN (:bundle) AND flagging.fid = :follow_fid AND reverse_flagging.fid = :follow_fid AND flagging.entity_id = :uid
      AND reverse_flagging.uid = :uid AND favorite_node.fid = :favorite_fid', 0, $display_items, array(
        ':bundle' => $bundle,
        ':follow_fid' => $follow_user->fid,
        ':uid' => $user->uid,
        ':favorite_fid' => $favorite->fid
      ))->fetchCol();

      break;

    case 'im_following':
      $matches = db_query_range('SELECT flagging.entity_id
        FROM flagging
        INNER JOIN node on node.nid = flagging.entity_id
        WHERE node.type IN (:bundle) AND flagging.uid = :uid AND flagging.fid = :favorite_fid', 0, $display_items, array(
        ':bundle' => $bundle,
        ':uid' => $user->uid,
        ':favorite_fid' => $favorite->fid
      ))->fetchCol();

      break;

    case 'innovation':
    case 'funding':
    case 'resource':
    case 'event':
      $matches = db_query_range('SELECT node.nid FROM node
        WHERE node.type IN (:bundle) AND node.uid = :uid ORDER BY node.changed DESC', 0, $display_items, array(
        ':bundle' => $filter,
        ':uid' => $user->uid
      ))->fetchCol();

      break;

    case 'net_innovation':
    case 'net_funding':
    case 'net_resource':
    case 'net_event':
    case 'net_organization':
    case 'net_program':

      $matches = db_query_range('SELECT flagging.entity_id
        FROM flagging
        INNER JOIN node on node.nid = flagging.entity_id
        WHERE node.type IN (:bundle) AND flagging.uid = :uid AND flagging.fid = :favorite_fid', 0, $display_items, array(
        ':bundle' => substr($filter, 4),
        ':uid' => $user->uid,
        ':favorite_fid' => $favorite->fid
      ))->fetchCol();

      break;

    case 'net_users':

      $matches = db_query('SELECT flagging.uid FROM flagging
    INNER JOIN flagging reverse_flagging on flagging.uid = reverse_flagging.entity_id
    WHERE flagging.fid = :fid AND reverse_flagging.fid  = :fid
    AND flagging.entity_id = :uid AND reverse_flagging.uid = :uid', array(
        ':fid' => $follow_user->fid,
        ':uid' => $user->uid
      ))->fetchCol();

      break;

    default:

      $matches = db_query_range("SELECT DISTINCT node.nid  FROM node
      LEFT JOIN field_data_field_term_sector sector_1 ON node.nid = sector_1.entity_id AND (sector_1.entity_type = 'node' AND sector_1.deleted = '0')
      INNER JOIN taxonomy_term_data  ON sector_1.field_term_sector_tid = taxonomy_term_data.tid
      INNER JOIN field_data_field_term_sector sector_2 ON taxonomy_term_data.tid = sector_2.field_term_sector_tid AND (sector_2.entity_type = 'user' AND sector_2.deleted = '0')
      INNER JOIN users ON sector_2.entity_id = users.uid
      WHERE (( (users.uid = :uid ) )AND(( (node.status = '1') AND (node.type IN (:bundle)) ))) ORDER BY node.changed DESC ", 0, $display_items, array(
        ':uid' => $user->uid,
        ':bundle' => $bundle
      ))->fetchCol();

      break;
  }

  return $matches;
}

function dashboard_recommended_innovations_form($form, &$form_state) {

  $bundle = array('innovation');
  $filter = (!empty($_GET) && !empty($_GET['stdfilter'])) ? $_GET['stdfilter'] : 'my_sectors';
  $matches = dashboard_recommendation_engine($bundle, $filter);
  $payload = array();
  $inc = 0;
  $user_model = FALSE;

  $form['sectors'] = array(
    '#type' => 'submit',
    '#value' => t('My Sectors')
  );
  $form['topics'] = array(
    '#type' => 'submit',
    '#value' => t('My Topics')
  );
  $form['skills'] = array(
    '#type' => 'submit',
    '#value' => t('My Skills')
  );
  $form['friends'] = array(
    '#type' => 'submit',
    '#value' => t('My Friends')
  );
  $form['following'] = array(
    '#type' => 'submit',
    '#value' => t('I\'m Following')
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => '',
    '#prefix' => '<div style="display: none;">',
    '#suffix' => '</div>',
    '#weight' => 0,
  );


  foreach ($matches as $key => $sector_match) {
    $inc += 1;
    $entity = entity_view('node', array(node_load($sector_match)), 'listing');
    if (!empty($entity)) {
      $payload[$key + $inc] = render($entity);
    }
  }

  $payload = array(
    '#theme' => 'item_list',
    '#items' => $payload,
    '#type' => 'ul',
    '#attributes' => array('class' => 'list-class'),
  );

  $form['updates'] = array(
    '#type' => 'item',
    '#markup' => drupal_render($payload),
    '#weight' => 5,
    '#suffix' => '<div class="dashboard__all-data-button"><a class="button button--highlight" href="/data">See all Exchange Data</a></div>'
  );

  return $form;
}

function dashboard_recommended_innovations_form_validate($form, &$form_state) {
  $test = 1;
}

function dashboard_recommended_innovations_form_submit($form, &$form_state) {
  $filter = 'my_sectors';
  if (!empty($form_state['triggering_element']['#value'])) {

    switch ($form_state['triggering_element']['#value']) {
      case 'My Sectors':
        $filter = 'my_sectors';
        break;
      case 'My Topics':
        $filter = 'my_topics';
        break;
      case 'My Skills':
        $filter = 'my_skills';
        break;
      case 'My Friends':
        $filter = 'my_friends';
        break;
      case 'I\'m Following':
        $filter = 'im_following';
        break;
    }

    $form_state['redirect'] = array(
      'dashboard',
      array(
        'query' => array(
          'qt-dashboard' => 2,
          'stdfilter' => $filter
        ),
      ),
    );
    drupal_redirect_form($form_state);
  }
}

function dashboard_recommended_funding_form($form, &$form_state) {

  $bundle = array('funding');
  $filter = (!empty($_GET) && !empty($_GET['stdfilter'])) ? $_GET['stdfilter'] : 'sectors';
  $matches = dashboard_recommendation_engine($bundle, $filter);
  $payload = array();
  $inc = 0;
  $user_model = FALSE;

  $form['sectors'] = array(
    '#type' => 'submit',
    '#value' => t('My Sectors')
  );
  $form['topics'] = array(
    '#type' => 'submit',
    '#value' => t('My Topics')
  );
  $form['skills'] = array(
    '#type' => 'submit',
    '#value' => t('My Skills')
  );
  $form['friends'] = array(
    '#type' => 'submit',
    '#value' => t('My Friends')
  );
  $form['following'] = array(
    '#type' => 'submit',
    '#value' => t('I\'m Following')
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => '',
    '#prefix' => '<div style="display: none;">',
    '#suffix' => '</div>',
    '#weight' => 0,
  );


  foreach ($matches as $key => $sector_match) {
    $inc += 1;
    $entity = entity_view('node', array(node_load($sector_match)), 'listing');
    if (!empty($entity)) {
      $payload[$key + $inc] = render($entity);
    }
  }

  $payload = array(
    '#theme' => 'item_list',
    '#items' => $payload,
    '#type' => 'ul',
    '#attributes' => array('class' => 'list-class'),
  );

  $form['updates'] = array(
    '#type' => 'item',
    '#markup' => drupal_render($payload),
    '#weight' => 5,
    '#suffix' => '<div class="dashboard__all-data-button"><a class="button button--highlight" href="/data">See all Exchange Data</a></div>'
  );

  return $form;
}

function dashboard_recommended_funding_form_validate($form, &$form_state) {
  $test = 1;
}

function dashboard_recommended_funding_form_submit($form, &$form_state) {
  $filter = 'my_sectors';
  if (!empty($form_state['triggering_element']['#value'])) {

    switch ($form_state['triggering_element']['#value']) {
      case 'My Sectors':
        $filter = 'my_sectors';
        break;
      case 'My Topics':
        $filter = 'my_topics';
        break;
      case 'My Skills':
        $filter = 'my_skills';
        break;
      case 'My Friends':
        $filter = 'my_friends';
        break;
      case 'I\'m Following':
        $filter = 'im_following';
        break;
    }

    $form_state['redirect'] = array(
      'dashboard',
      array(
        'query' => array(
          'qt-dashboard' => 3,
          'stdfilter' => $filter
        ),
      ),
    );
    drupal_redirect_form($form_state);
  }
}

function dashboard_my_portfolio_form($form, &$form_state) {

  $bundle = array('innovation', 'funding', 'resource', 'event');
  $filter = (!empty($_GET) && !empty($_GET['pfilter'])) ? $_GET['pfilter'] : 'innovation';
  $matches = dashboard_recommendation_engine($bundle, $filter);
  $payload = array();
  $inc = 0;

  $form['innovation'] = array(
    '#type' => 'submit',
    '#value' => t('My Innovations')
  );
  $form['funding'] = array(
    '#type' => 'submit',
    '#value' => t('My Funding Opportunities')
  );
  $form['resource'] = array(
    '#type' => 'submit',
    '#value' => t('My Resources')
  );
  $form['event'] = array(
    '#type' => 'submit',
    '#value' => t('My Events')
  );


  if (!empty($matches)) {
    foreach ($matches as $key => $sector_match) {
      $inc += 1;
      $favorite = flag_load('favorite');
      $entity = entity_view('node', array(node_load($sector_match)), 'listing');
      if (!empty($entity)) {
        $payload[$key + $inc] = render($entity);
      }
    }
  }
  else {
    switch ($filter) {
      case 'innovation':
        $payload[] = 'You haven\'t created any innovations! Click ' . l('here', 'node/add/innovation') . ' to add your innovations.';
        break;
      case 'funding':
        $payload[] = 'You haven\'t created any funding opportunities! Click ' . l('here', 'node/add/funding') . ' to add your funding opportunities.';
        break;
      case 'resource':
        $payload[] = 'You haven\'t created any resources! Click ' . l('here', 'node/add/resources') . ' to add your resources.';
        break;
      case 'event':
        $payload[] = 'You haven\'t created any events! Click ' . l('here', 'node/add/event') . ' to add your events.';
        break;
    }
  }

  $payload = array(
    '#theme' => 'item_list',
    '#items' => $payload,
    '#type' => 'ul',
    '#attributes' => array('class' => 'list-class'),
  );

  $form['updates'] = array(
    '#type' => 'item',
    '#markup' => drupal_render($payload),
    '#weight' => 5,
    '#suffix' => '<div class="dashboard__all-data-button"><a class="button button--highlight" href="/data">See all Exchange Data</a></div>'
  );

  return $form;
}

function dashboard_my_portfolio_form_validate($form, &$form_state) {
  $test = 1;
}

function dashboard_my_portfolio_form_submit($form, &$form_state) {
  $filter = 'innovations';

  if (!empty($form_state['triggering_element']['#value'])) {

    switch ($form_state['triggering_element']['#value']) {
      case 'My Innovations':
        $filter = 'innovation';
        break;
      case 'My Funding Opportunities':
        $filter = 'funding';
        break;
      case 'My Resources':
        $filter = 'resource';
        break;
      case 'My Events':
        $filter = 'event';
        break;
    }

    $form_state['redirect'] = array(
      'dashboard',
      array(
        'query' => array(
          'qt-dashboard' => 1,
          'pfilter' => $filter
        ),
      ),
    );
    drupal_redirect_form($form_state);
  }
}

function dashboard_my_network_form($form, &$form_state) {

  $bundle = array(
    'net_users',
    'net_innovation',
    'net_funding',
    'net_resource',
    'net_event',
    'net_organization',
    'net_program'
  );
  $filter = (!empty($_GET) && !empty($_GET['nfilter'])) ? $_GET['nfilter'] : 'net_users';
  $matches = dashboard_recommendation_engine($bundle, $filter);
  $payload = array();
  $inc = 0;

  $form['net_users'] = array(
    '#type' => 'submit',
    '#value' => t('Users')
  );
  $form['net_innovation'] = array(
    '#type' => 'submit',
    '#value' => t('Innovations')
  );
  $form['net_funding'] = array(
    '#type' => 'submit',
    '#value' => t('Funding Ops')
  );
  $form['net_resource'] = array(
    '#type' => 'submit',
    '#value' => t('Resources')
  );
  $form['net_event'] = array(
    '#type' => 'submit',
    '#value' => t('Events')
  );
  $form['net_organization'] = array(
    '#type' => 'submit',
    '#value' => t('Organizations')
  );
  $form['net_program'] = array(
    '#type' => 'submit',
    '#value' => t('Programs')
  );

  if (!empty($matches)) {
    if ($filter != 'net_users') {
      foreach ($matches as $key => $sector_match) {
        $inc += 1;
        $entity = entity_view('node', array(node_load($sector_match)), 'listing');
        if (!empty($entity)) {
          $payload[$key + $inc] = render($entity);
        }
      }
    }
    else {
      foreach ($matches as $key => $sector_match) {
        $inc += 1;
        $entity = entity_view('user', array(user_load($sector_match)), 'listing');
        if (!empty($entity)) {
          $payload[$key + $inc] = render($entity);
        }
      }
    }
  }
  else {

    switch ($filter) {
      case 'net_users':
        $payload[] = 'You haven\'t created any followed any users! Click ' . l('here', 'users') . ' to follow new users';
        break;
      case 'net_innovation':
        $payload[] = 'You haven\'t created any followed any innovations! Click ' . l('here', 'innovation') . ' to follow new innovations';
        break;
      case 'net_funding':
        $payload[] = 'You haven\'t created any followed any fundings! Click ' . l('here', 'funding') . ' to follow new fundings';
        break;
      case 'net_resource':
        $payload[] = 'You haven\'t created any followed any resources! Click ' . l('here', 'resource') . ' to follow new resources';
        break;
      case 'net_event':
        $payload[] = 'You haven\'t created any followed any events! Click ' . l('here', 'event') . ' to follow new events';
        break;
      case 'net_organization':
        $payload[] = 'You haven\'t created any followed any organizations! Click ' . l('here', 'organization') . ' to follow new organizations';
        break;
      case 'net_program':
        $payload[] = 'You haven\'t created any followed any programs! Click ' . l('here', 'program') . ' to follow new programs';
        break;
    }
  }

  $payload = array(
    '#theme' => 'item_list',
    '#items' => $payload,
    '#type' => 'ul',
    '#attributes' => array('class' => 'list-class'),
  );

  $form['updates'] = array(
    '#type' => 'item',
    '#markup' => drupal_render($payload),
    '#weight' => 5,
    '#suffix' => '<div class="dashboard__all-data-button"><a class="button button--highlight" href="/data">See all Exchange Data</a></div>'
  );

  return $form;
}

function dashboard_my_network_form_validate($form, &$form_state) {
  $test = 1;
}

function dashboard_my_network_form_submit($form, &$form_state) {
  $filter = 'net_users';

  if (!empty($form_state['triggering_element']['#value'])) {

    switch ($form_state['triggering_element']['#value']) {
      case 'Users':
        $filter = 'net_users';
        break;
      case 'Innovations':
        $filter = 'net_innovation';
        break;
      case 'Funding Ops':
        $filter = 'net_funding';
        break;
      case 'Resources':
        $filter = 'net_resource';
        break;
      case 'Events':
        $filter = 'net_event';
        break;
      case 'Organizations':
        $filter = 'net_organization';
        break;
      case 'Programs':
        $filter = 'net_program';
        break;
    }

    $form_state['redirect'] = array(
      'dashboard',
      array(
        'query' => array(
          'qt-dashboard' => 4,
          'nfilter' => $filter
        ),
      ),
    );
    drupal_redirect_form($form_state);
  }
}