<?php
/**
 * @file
 * Code for the GIE Dashboard feature.
 */

include_once 'gie_dashboard.features.inc';


/*
 * Implements hook_ctools_plugin_directory()
 */
function gie_dashboard_ctools_plugin_directory($owner, $plugin_type) {
    if ($owner == 'ctools' && $plugin_type == 'content_types') {
        return 'plugins/' . $plugin_type;
    }
}

/**
 * Implements hook_search_api_solr_query_alter().
 * 
 * Adds multiple IDs for MLT call
 */
function gie_dashboard_search_api_solr_query_alter(array &$call_args, SearchApiQueryInterface $query) {
  $id = search_api_solr_site_hash();
  
  // Make sure it's the query we want, could also check reference of query
  if ("id:\"{$id}-default_node_index-315\"" == $call_args['query']) {
    $call_args['query'] = "id:(\"{$id}-default_node_index-315\" OR \"{$id}-default_node_index-484\")";
  }
}
