---
classes: 
  - forumone::solr
  - forumone::varnish
  - forumone::nodejs
  - forumone::ruby
  - redis

forumone::webserver::webserver: nginx

forumone::php::prefix: "php56u"

forumone::php::modules:
  - opcache
  - pecl-redis
  
forumone::solr::collections:  
  drupal: 
    order: 1
