<?php
/**
 * @file
 * Code for the GIE General feature.
 */

include_once 'gie_general.features.inc';

/**
 * Implements hook_menu_alter().
 * - Alter title of 'User Account' link.
 * - Alter Dashboard so only logged in users see link. 
 */
function gie_general_menu_alter(&$items) {
  $items['user']['title callback'] = '_gie_general_welcome';
  $items['dashboard']['access callback'] = 'user_is_logged_in';
}

/**
 * Callback to generate dynamic Welcome text.
 */
function _gie_general_welcome() {
  if (user_is_logged_in()) {
    $user = entity_metadata_wrapper('user', $GLOBALS['user']);
    $first_name = $user->field_user_firstname->value();

    // Temporary if statement to place filled in name
    // TODO: remove this statement if first name becomes required
    if (!empty($first_name)) {
      $name = $first_name;
    } else {
      $name = $user->name->value();
    }
    return t('Welcome, ') . $name . '!';
  } else {
    return t('User account');
  }
}

/**
 * Implements hook_block_info().
 */
function gie_general_block_info() {
  $blocks = array();

  $blocks['innovation_submenu'] = array(
    'info' => t('GIE Innovation submenu'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function gie_general_block_view($delta = '') {
  $block = array();

  switch($delta) {
    case 'innovation_submenu':
      $block['subject'] = '';
      $block['content'] = _gie_general_contents($delta);
      break;
  }

  return $block;
}

/**
 * Returns block content.
 * - Innovation Submenu links
 */
function _gie_general_contents($block_id) {
  $block = array();

  switch($block_id) {
    case 'innovation_submenu':
      $block = array(
        'browse_all' => array(
          '#type' => 'link',
          '#title' => t('Browse all innovations'),
          '#href' => 'innovations',
          '#attributes' => array(
            'class' => array('tb-megamenu-big-button has-icon-innovation'),
          ),
        ),
      );
      if (user_access('create innovation content')) {
        $block += array(
          'add_innovation' => array(
            '#type' => 'link',
            '#title' => t('Add an innovation'),
            '#href' => 'node/add/innovation',
            '#attributes' => array(
              'class' => array('tb-megamenu-big-button has-icon-add'),
            ),
          ),
        );
      }
      $block += array(
        'find_innovations' => array(
          '#type' => 'link',
          '#title' => t('Find other innovators'),
          '#href' => 'members/field_user_type/29',
          '#attributes' => array(
            'class' => array('tb-megamenu-big-button has-icon-innovator'),
          ),
        ),
      );
      break;
  }

  return $block;
}

/**
 * Implements hook_node_presave().
 * - Set node author to Point of Contact for
 * - new innovations/programs/organizations when
 * - point of contact field is empty upon node creation.
 */
function gie_general_node_presave($node) {
  switch($node->type) {
    case 'innovation':
      $wrapper = entity_metadata_wrapper('node', $node);
      $poc = $wrapper->field_innovation_poc->value();
      if (!$poc && !$node->nid) {
        $user = user_load($node->uid);
        $wrapper->field_innovation_poc->set($user);
      }
      break;
    case 'program':
      $wrapper = entity_metadata_wrapper('node', $node);
      $poc = $wrapper->field_program_poc->value();
      if (!$poc && !$node->nid) {
        $user = user_load($node->uid);
        $wrapper->field_program_poc->set($user);
      }
      break;
    case 'organization':
      $wrapper = entity_metadata_wrapper('node', $node);
      $poc = $wrapper->field_org_poc->value();
      if (!$poc && !$node->nid) {
        $user = user_load($node->uid);
        $wrapper->field_org_poc->set($user);
      }
      break;
  }
}
