<?php
/**
 * @file
 * Code for the GIE Search feature.
 */

include_once 'gie_search.features.inc';

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function gie_search_form_search_api_page_search_form_alter(&$form, &$form_state, $form_id) {
  // Change the Search Page block's placeholder
  $form['keys_1']['#attributes']['placeholder'] = 'START SEARCHING...';
}

/**
 * Force attributes on the Elasticsearch API index
 * 
 * @param array $defaults
 */
function gie_search_default_search_api_index_alter(array &$defaults) {
  $api_index = variable_get('elasticsearch_index', array());

  foreach ($api_index as $id => $index) {
    if (TRUE === isset($defaults[$id])) {
      $defaults[$index['machine_name']] = clone($defaults[$id]);
      foreach ($index as $key => $value) {
        $defaults[$index['machine_name']]->{$key} = $value;
      }

      unset($defaults[$id]);
    }
  }
}