<?php
/**
 * @file
 * Drupal needs this blank file.
 */

/**
 * Implements hook_menu_link_alter().
 */
function gie_user_redirect_menu_link_alter(&$item) {
  // Flag a link to be altered by hook_translated_menu_link_alter().
  // This is called only on menu rebuild, so we have to add this information
  // manually to the database on install. Clearing caches also helps.
  $paths = array('user/logout', 'user/login', 'user');
  if (in_array($item['link_path'], $paths)) {
    $item['options']['alter'] = TRUE;
  }
}

/**
 * Implements hook_translated_menu_link_alter().
 */
function gie_user_redirect_translated_menu_link_alter(&$item, $map) {
  $paths = array('user/login', 'user');
  // Append the current path to URL.
  if ($item['link_path'] == 'user/logout' || (in_array($item['link_path'], $paths))) {
    $item['localized_options']['query'] = array('destination' => current_path());
  }
}