<?php
/**
 * @file
 * Drupal needs this blank file.
 */


/**
 * @param $form
 * @param $form_state
 */
function gie_security_form_node_form_alter(&$form) {
  $types = array(
    'innovation',
    'funding',
    'resource',
    'event',
    'organization',
    'program',
    'blogs',
    'news'
  );

  $admin_role = user_role_load_by_name('administrator');
  // Set field visibility based on whether the user is an admin
  if (in_array($form['type']['#value'], $types) && !(user_has_role($admin_role->rid))) {
    $form['#submit'][] = 'gie_security_new_relic_insights';
  }
}

function gie_security_new_relic_insights($form, $form_state) {
  if (module_exists('new_relic_insights') && function_exists('new_relic_insights_post_event') && !empty($form_state['values']['title_field']['und'][0]['value'])) {
    new_relic_insights_post_event($form_state['values']['title_field']['und'][0]['value']);
  }
}